# Generated by Django 3.1.3 on 2020-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='categories.Categories'),
        ),
    ]
